---
- name: LST ESX stor and templates configuration
  gather_facts: false
  hosts: localhost
  vars_files:
    - group_vars/all.yml 
  vars:
    templates_clone_sleeper: []
    vm_create_sleeper: []

  tasks:
  - name: Clone VM to template
    vmware_guest:
      hostname: "{{vcenter_hostname}}"
      username: "{{vcenter_username}}"
      password: "{{vcenter_password}}"
      validate_certs: False
      name: "{{esx}}_{{st_type}}_tmp_{{ platform }}"
      template: "t_{{ platform }}"
      datacenter: "{{datacenter}}"
      cluster: "{{cluster}}"
      folder: "{{folder}}"
      datastore: "ns-{{st_type}}-{{ esx }}" 
      state: poweredoff
      is_template: yes
    async: 3000
    poll: 0
    register: _templates_clone_sleeper
  
  - set_fact:
     templates_clone_sleeper: "{{ templates_clone_sleeper  + _templates_clone_sleeper.results }}"
  
